# -*- coding: utf-8 -*-
"""Credit_Risk_Assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hsXYeaO8aQ6TWpy9gcz2VEIqt3T41jYG
"""

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

uci = pd.read_csv("UCI_Credit_Card.csv")
german = pd.read_csv("german_credit_data.csv")

print(german.columns)

from google.colab import files
uploaded = files.upload()

uci = pd.read_csv("UCI_Credit_Card.csv")
german = pd.read_csv("german_credit_data.csv")

uci.rename(columns={
    'default.payment.next.month': 'default'
}, inplace=True)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier

from imblearn.over_sampling import SMOTE

uploaded = files.upload()

uci = pd.read_csv("UCI_Credit_Card.csv")
german = pd.read_csv("german_credit_data.csv")

print("Datasets Uploaded ✅")

print("UCI DataFrame columns:", uci.columns)

uci.rename(columns={
    'target': 'default'
}, inplace=True)


german.drop(columns=['Unnamed: 0'], inplace=True)

german.fillna("Unknown", inplace=True)

german['default'] = np.where(
    (german['Credit amount'] > german['Credit amount'].median()) &
    (german['Duration'] > german['Duration'].median()),
    1, 0
)

print("Target column created for German Dataset ✅")


def train_models(data, name):

    print(f"\n========== {name} ==========")

    X = data.drop('default', axis=1)
    y = data['default']

    X = pd.get_dummies(X, drop_first=True)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=0.2,
        random_state=42,
        stratify=y
    )

    smote = SMOTE(random_state=42)
    X_train, y_train = smote.fit_resample(X_train, y_train)

    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    rf = RandomForestClassifier(n_estimators=200, random_state=42)

    xgb = XGBClassifier(
        eval_metric='logloss',
        random_state=42
    )

    lr = LogisticRegression(max_iter=1000)

    models = {
        "Random Forest": rf,
        "XGBoost": xgb,
        "Logistic Regression": lr
    }

    results = {}

    for name_model, model in models.items():

        model.fit(X_train, y_train)

        pred = model.predict(X_test)
        prob = model.predict_proba(X_test)[:,1]

        auc = roc_auc_score(y_test, prob)
        results[name_model] = auc

        print(f"\n{name_model}")
        print(classification_report(y_test, pred))
        print("ROC-AUC:", auc)

        plt.figure()
        sns.heatmap(confusion_matrix(y_test, pred),
                    annot=True, fmt="d")
        plt.title(f"{name_model} Confusion Matrix")
        plt.show()

    print("\n🏆 BEST MODEL:",
          max(results, key=results.get))

train_models(uci, "UCI Credit Card Dataset")

train_models(german, "German Credit Dataset")

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

X = uci.drop("default", axis=1)
y = uci["default"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = Sequential()

model.add(Dense(32, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=20, batch_size=32, verbose=1)

y_pred = (model.predict(X_test) > 0.5).astype(int)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

from tensorflow.keras.layers import Conv1D, Flatten, MaxPooling1D
from tensorflow.keras.models import Sequential

X_train_cnn = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test_cnn = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

cnn_model = Sequential()

cnn_model.add(Conv1D(32, 2, activation='relu', input_shape=(X_train_cnn.shape[1],1)))
cnn_model.add(MaxPooling1D(2))
cnn_model.add(Flatten())

cnn_model.add(Dense(16, activation='relu'))
cnn_model.add(Dense(1, activation='sigmoid'))

cnn_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

cnn_model.fit(X_train_cnn, y_train, epochs=20, batch_size=32)

y_pred_cnn = (cnn_model.predict(X_test_cnn) > 0.5).astype(int)

print("CNN Accuracy:", accuracy_score(y_test, y_pred_cnn))
print(confusion_matrix(y_test, y_pred_cnn))
print(classification_report(y_test, y_pred_cnn))

import pandas as pd
import zipfile
from google.colab import files

uploaded = files.upload()

# -------- UCI ZIP --------
with zipfile.ZipFile("UCI_Credit_Card.csv.zip", 'r') as zip_ref:
    zip_ref.extract("UCI_Credit_Card.csv")

uci = pd.read_csv("UCI_Credit_Card.csv")

# -------- German ZIP --------
with zipfile.ZipFile("german_credit_data.csv.zip", 'r') as zip_ref:
    zip_ref.extract("german_credit_data.csv")

german = pd.read_csv("german_credit_data.csv")

print("Both datasets loaded successfully ✅")

# RNN + LSTM FOR BOTH DATASETS

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, LSTM, Dense, Input

# DATA PREPARATION FUNCTION

def prepare_data_for_dl(data, dataset_name):
    print(f"\n===== Preparing {dataset_name} Dataset =====")

    data = data.copy()

    # UCI dataset target fix
    if dataset_name == "UCI Credit Card Dataset":
        if "default" not in data.columns:
            data.rename(columns={"default.payment.next.month": "default"}, inplace=True)

    # German dataset preprocessing
    if dataset_name == "German Credit Dataset":
        if "Unnamed: 0" in data.columns:
            data.drop(columns=["Unnamed: 0"], inplace=True)

        data.fillna("Unknown", inplace=True)

        if "default" not in data.columns:
            data["default"] = np.where(
                (data["Credit amount"] > data["Credit amount"].median()) &
                (data["Duration"] > data["Duration"].median()),
                1, 0
            )

    # Features and target
    X = data.drop("default", axis=1)
    y = data["default"]

    # Convert categorical to numeric
    X = pd.get_dummies(X, drop_first=True)

    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=0.2,
        random_state=42,
        stratify=y
    )

    # Scaling
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    # Reshape for RNN/LSTM
    X_train_seq = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
    X_test_seq = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

    return X_train_seq, X_test_seq, y_train, y_test


# RNN FUNCTION

def run_rnn(data, dataset_name):
    X_train_seq, X_test_seq, y_train, y_test = prepare_data_for_dl(data, dataset_name)

    print(f"\n===== RNN on {dataset_name} =====")

    rnn_model = Sequential()
    rnn_model.add(Input(shape=(X_train_seq.shape[1], 1)))
    rnn_model.add(SimpleRNN(32, activation='tanh'))
    rnn_model.add(Dense(16, activation='relu'))
    rnn_model.add(Dense(1, activation='sigmoid'))

    rnn_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

    rnn_model.fit(
        X_train_seq, y_train,
        epochs=20,
        batch_size=32,
        validation_split=0.2,
        verbose=1
    )

    y_pred_rnn = (rnn_model.predict(X_test_seq) > 0.5).astype(int)

    print("\nRNN Accuracy:", accuracy_score(y_test, y_pred_rnn))
    print(confusion_matrix(y_test, y_pred_rnn))
    print(classification_report(y_test, y_pred_rnn))


# LSTM FUNCTION

def run_lstm(data, dataset_name):
    X_train_seq, X_test_seq, y_train, y_test = prepare_data_for_dl(data, dataset_name)

    print(f"\n===== LSTM on {dataset_name} =====")

    lstm_model = Sequential()
    lstm_model.add(Input(shape=(X_train_seq.shape[1], 1)))
    lstm_model.add(LSTM(32, activation='tanh'))
    lstm_model.add(Dense(16, activation='relu'))
    lstm_model.add(Dense(1, activation='sigmoid'))

    lstm_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

    lstm_model.fit(
        X_train_seq, y_train,
        epochs=20,
        batch_size=32,
        validation_split=0.2,
        verbose=1
    )

    y_pred_lstm = (lstm_model.predict(X_test_seq) > 0.5).astype(int)

    print("\nLSTM Accuracy:", accuracy_score(y_test, y_pred_lstm))
    print(confusion_matrix(y_test, y_pred_lstm))
    print(classification_report(y_test, y_pred_lstm))

# RUN ON BOTH DATASETS

run_rnn(uci, "UCI Credit Card Dataset")
run_lstm(uci, "UCI Credit Card Dataset")

run_rnn(german, "German Credit Dataset")
run_lstm(german, "German Credit Dataset")